/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs_pos;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Jason
 */
public final class AdminMain extends javax.swing.JFrame
{

    /**
     * Creates new form test
     */
    DatabaseQueries dbq = new DatabaseQueries();
    GetAdminInfo a = new GetAdminInfo();
    PasswordHashing pw = new PasswordHashing();
    //Initialize ArrayList to store username for undo purposes 
    ArrayList<String> tempUsername = new ArrayList<>();
    ArrayList<String> initialTaskIDS = new ArrayList<>();
    ArrayList<String> initialAssignedTo = new ArrayList<>();

    /**
     * Constructor for AdminMain GUI
     */
    public AdminMain()
    {
        super("View All Tasks");
        initComponents();
        this.setLocationRelativeTo(null);
    }

  
    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parent = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        usersBtn = new javax.swing.JPanel();
        ind_users = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        taskBtn = new javax.swing.JPanel();
        ind_tasks = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        logsBtn = new javax.swing.JPanel();
        ind_logs = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        logout_Btn = new javax.swing.JButton();
        myInfoBtn = new javax.swing.JPanel();
        ind_edit = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        signOffTaskBtn = new javax.swing.JPanel();
        ind_signOff = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        tasks_Panel = new javax.swing.JPanel();
        logs_Panel = new javax.swing.JPanel();
        signOffPanel = new javax.swing.JPanel();
        myInfo_Panel = new javax.swing.JPanel();
        users_Panel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        IDfield = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 1000));

        sidePanel.setBackground(new java.awt.Color(1, 50, 67));

        jLabel2.setBackground(new java.awt.Color(236, 236, 236));
        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(236, 236, 236));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Main Menu");

        usersBtn.setBackground(new java.awt.Color(1, 50, 67));
        usersBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        usersBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usersBtnMousePressed(evt);
            }
        });
        usersBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind_users.setOpaque(false);

        javax.swing.GroupLayout ind_usersLayout = new javax.swing.GroupLayout(ind_users);
        ind_users.setLayout(ind_usersLayout);
        ind_usersLayout.setHorizontalGroup(
            ind_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ind_usersLayout.setVerticalGroup(
            ind_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        usersBtn.add(ind_users, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 5, 50));

        jLabel1.setBackground(new java.awt.Color(236, 236, 236));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(236, 236, 236));
        jLabel1.setText("USERS");
        usersBtn.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 70, 40));

        taskBtn.setBackground(new java.awt.Color(1, 50, 67));
        taskBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        taskBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                taskBtnMousePressed(evt);
            }
        });
        taskBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind_tasks.setOpaque(false);

        javax.swing.GroupLayout ind_tasksLayout = new javax.swing.GroupLayout(ind_tasks);
        ind_tasks.setLayout(ind_tasksLayout);
        ind_tasksLayout.setHorizontalGroup(
            ind_tasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ind_tasksLayout.setVerticalGroup(
            ind_tasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        taskBtn.add(ind_tasks, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 5, 50));

        jLabel3.setBackground(new java.awt.Color(236, 236, 236));
        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(236, 236, 236));
        jLabel3.setText("TASKS");
        taskBtn.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 130, 40));

        logsBtn.setBackground(new java.awt.Color(1, 50, 67));
        logsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logsBtnMousePressed(evt);
            }
        });
        logsBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind_logs.setOpaque(false);

        javax.swing.GroupLayout ind_logsLayout = new javax.swing.GroupLayout(ind_logs);
        ind_logs.setLayout(ind_logsLayout);
        ind_logsLayout.setHorizontalGroup(
            ind_logsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ind_logsLayout.setVerticalGroup(
            ind_logsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        logsBtn.add(ind_logs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 5, 50));

        jLabel4.setBackground(new java.awt.Color(236, 236, 236));
        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(236, 236, 236));
        jLabel4.setText("HISTORY");
        logsBtn.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 80, 40));

        logout_Btn.setBackground(new java.awt.Color(204, 0, 0));
        logout_Btn.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        logout_Btn.setForeground(new java.awt.Color(255, 255, 255));
        logout_Btn.setText("LOG OUT");

        myInfoBtn.setBackground(new java.awt.Color(1, 50, 67));
        myInfoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        myInfoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                myInfoBtnMousePressed(evt);
            }
        });
        myInfoBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind_edit.setOpaque(false);

        javax.swing.GroupLayout ind_editLayout = new javax.swing.GroupLayout(ind_edit);
        ind_edit.setLayout(ind_editLayout);
        ind_editLayout.setHorizontalGroup(
            ind_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ind_editLayout.setVerticalGroup(
            ind_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        myInfoBtn.add(ind_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 5, 50));

        jLabel52.setBackground(new java.awt.Color(236, 236, 236));
        jLabel52.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(236, 236, 236));
        jLabel52.setText("MY INFO");
        myInfoBtn.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 120, 40));

        signOffTaskBtn.setBackground(new java.awt.Color(1, 50, 67));
        signOffTaskBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signOffTaskBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                signOffTaskBtnMousePressed(evt);
            }
        });
        signOffTaskBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind_signOff.setOpaque(false);

        javax.swing.GroupLayout ind_signOffLayout = new javax.swing.GroupLayout(ind_signOff);
        ind_signOff.setLayout(ind_signOffLayout);
        ind_signOffLayout.setHorizontalGroup(
            ind_signOffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ind_signOffLayout.setVerticalGroup(
            ind_signOffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        signOffTaskBtn.add(ind_signOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 5, 50));

        jLabel55.setBackground(new java.awt.Color(236, 236, 236));
        jLabel55.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(236, 236, 236));
        jLabel55.setText("SIGN OFF");
        signOffTaskBtn.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 120, 40));

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usersBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(taskBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
            .addComponent(logsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(myInfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logout_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(signOffTaskBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166)
                .addComponent(taskBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(myInfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signOffTaskBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        body.setLayout(new java.awt.CardLayout());

        tasks_Panel.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout tasks_PanelLayout = new javax.swing.GroupLayout(tasks_Panel);
        tasks_Panel.setLayout(tasks_PanelLayout);
        tasks_PanelLayout.setHorizontalGroup(
            tasks_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1211, Short.MAX_VALUE)
        );
        tasks_PanelLayout.setVerticalGroup(
            tasks_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 674, Short.MAX_VALUE)
        );

        body.add(tasks_Panel, "card4");

        logs_Panel.setBackground(new java.awt.Color(204, 204, 204));
        logs_Panel.setPreferredSize(new java.awt.Dimension(1146, 674));

        javax.swing.GroupLayout logs_PanelLayout = new javax.swing.GroupLayout(logs_Panel);
        logs_Panel.setLayout(logs_PanelLayout);
        logs_PanelLayout.setHorizontalGroup(
            logs_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1211, Short.MAX_VALUE)
        );
        logs_PanelLayout.setVerticalGroup(
            logs_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 674, Short.MAX_VALUE)
        );

        body.add(logs_Panel, "card2");

        javax.swing.GroupLayout signOffPanelLayout = new javax.swing.GroupLayout(signOffPanel);
        signOffPanel.setLayout(signOffPanelLayout);
        signOffPanelLayout.setHorizontalGroup(
            signOffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1211, Short.MAX_VALUE)
        );
        signOffPanelLayout.setVerticalGroup(
            signOffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 674, Short.MAX_VALUE)
        );

        body.add(signOffPanel, "card6");

        javax.swing.GroupLayout myInfo_PanelLayout = new javax.swing.GroupLayout(myInfo_Panel);
        myInfo_Panel.setLayout(myInfo_PanelLayout);
        myInfo_PanelLayout.setHorizontalGroup(
            myInfo_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1211, Short.MAX_VALUE)
        );
        myInfo_PanelLayout.setVerticalGroup(
            myInfo_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 674, Short.MAX_VALUE)
        );

        body.add(myInfo_Panel, "card5");

        users_Panel.setBackground(new java.awt.Color(204, 204, 204));
        users_Panel.setPreferredSize(new java.awt.Dimension(1146, 674));

        javax.swing.GroupLayout users_PanelLayout = new javax.swing.GroupLayout(users_Panel);
        users_Panel.setLayout(users_PanelLayout);
        users_PanelLayout.setHorizontalGroup(
            users_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1211, Short.MAX_VALUE)
        );
        users_PanelLayout.setVerticalGroup(
            users_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 674, Short.MAX_VALUE)
        );

        body.add(users_Panel, "card3");

        jPanel1.setBackground(new java.awt.Color(1, 50, 67));

        jLabel10.setBackground(new java.awt.Color(236, 236, 236));
        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(236, 236, 236));
        jLabel10.setText("Admin ID :");

        IDfield.setBackground(new java.awt.Color(236, 236, 236));
        IDfield.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        IDfield.setForeground(new java.awt.Color(236, 236, 236));
        IDfield.setText("" + a.getAdmin_ID());

        jLabel19.setBackground(new java.awt.Color(236, 236, 236));
        jLabel19.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(236, 236, 236));
        jLabel19.setText("Name :");

        jLabel20.setBackground(new java.awt.Color(236, 236, 236));
        jLabel20.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(236, 236, 236));
        jLabel20.setText(a.getaFname()+" "+a.getaLname());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IDfield, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(IDfield, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout parentLayout = new javax.swing.GroupLayout(parent);
        parent.setLayout(parentLayout);
        parentLayout.setHorizontalGroup(
            parentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parentLayout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(parentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        parentLayout.setVerticalGroup(
            parentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parentLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(parent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usersBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersBtnMousePressed
        resetColor(taskBtn);
        setColor(usersBtn);
        resetColor(logsBtn);
        resetColor(myInfoBtn);
        resetColor(signOffTaskBtn);

        ind_tasks.setOpaque(false);
        ind_users.setOpaque(true);
        ind_logs.setOpaque(false);
        ind_edit.setOpaque(false);
        ind_signOff.setOpaque(false);

        logs_Panel.setVisible(false);
        users_Panel.setVisible(true);
        tasks_Panel.setVisible(false);
        myInfo_Panel.setVisible(false);
        signOffPanel.setVisible(false);
    }//GEN-LAST:event_usersBtnMousePressed

    private void taskBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taskBtnMousePressed
        setColor(taskBtn);
        resetColor(usersBtn);
        resetColor(logsBtn);
        resetColor(myInfoBtn);
        resetColor(signOffTaskBtn);

        ind_tasks.setOpaque(true);
        ind_users.setOpaque(false);
        ind_logs.setOpaque(false);
        ind_edit.setOpaque(false);
        ind_signOff.setOpaque(false);

        logs_Panel.setVisible(false);
        users_Panel.setVisible(false);
        tasks_Panel.setVisible(true);
        myInfo_Panel.setVisible(false);
        signOffPanel.setVisible(false);
    }//GEN-LAST:event_taskBtnMousePressed

    private void logsBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logsBtnMousePressed
        // TODO add your handling code here:
        resetColor(taskBtn);
        resetColor(usersBtn);
        setColor(logsBtn);
        resetColor(myInfoBtn);
        resetColor(signOffTaskBtn);

        ind_tasks.setOpaque(false);
        ind_users.setOpaque(false);
        ind_logs.setOpaque(true);
        ind_edit.setOpaque(false);
        ind_signOff.setOpaque(false);

        logs_Panel.setVisible(true);
        users_Panel.setVisible(false);
        tasks_Panel.setVisible(false);
        myInfo_Panel.setVisible(false);
        signOffPanel.setVisible(false);
    }//GEN-LAST:event_logsBtnMousePressed

    private void myInfoBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myInfoBtnMousePressed
        // TODO add your handling code here:
        resetColor(taskBtn);
        resetColor(usersBtn);
        resetColor(logsBtn);
        setColor(myInfoBtn);
        resetColor(signOffTaskBtn);

        ind_tasks.setOpaque(false);
        ind_users.setOpaque(false);
        ind_logs.setOpaque(false);
        ind_edit.setOpaque(true);
        ind_signOff.setOpaque(false);

        logs_Panel.setVisible(false);
        users_Panel.setVisible(false);
        tasks_Panel.setVisible(false);
        myInfo_Panel.setVisible(true);
        signOffPanel.setVisible(false);
    }//GEN-LAST:event_myInfoBtnMousePressed

    private void signOffTaskBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signOffTaskBtnMousePressed
        resetColor(taskBtn);
        resetColor(usersBtn);
        resetColor(logsBtn);
        resetColor(myInfoBtn);
        setColor(signOffTaskBtn);

        ind_tasks.setOpaque(false);
        ind_users.setOpaque(false);
        ind_logs.setOpaque(false);
        ind_edit.setOpaque(false);
        ind_signOff.setOpaque(true);

        logs_Panel.setVisible(false);
        users_Panel.setVisible(false);
        tasks_Panel.setVisible(false);
        myInfo_Panel.setVisible(false);
        signOffPanel.setVisible(true);
    }//GEN-LAST:event_signOffTaskBtnMousePressed

    //Function to check if the original password matches with the database and if the new password matches with the confirm new password
    public boolean validate(String usrname, String oldPass,
            String newPass, String conNewPass) throws SQLException
    {
        boolean cond;

        cond = (oldPass.equals(dbq.getPassword(usrname, oldPass)))
                && (newPass.equals(conNewPass));
        return cond;
    }

    /**
     * @param args the command line arguments
     */
    void setColor(JPanel panel)
    {

        panel.setBackground(new Color(44, 62, 80));
    }

    void resetColor(JPanel panel)
    {
        panel.setBackground(new Color(1, 50, 67));
    }


    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch ( ClassNotFoundException ex )
        {
            java.util.logging.Logger.getLogger(AdminMain.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch ( InstantiationException ex )
        {
            java.util.logging.Logger.getLogger(AdminMain.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch ( IllegalAccessException ex )
        {
            java.util.logging.Logger.getLogger(AdminMain.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch ( javax.swing.UnsupportedLookAndFeelException ex )
        {
            java.util.logging.Logger.getLogger(AdminMain.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new AdminMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDfield;
    private javax.swing.JPanel body;
    private javax.swing.JPanel ind_edit;
    private javax.swing.JPanel ind_logs;
    private javax.swing.JPanel ind_signOff;
    private javax.swing.JPanel ind_tasks;
    private javax.swing.JPanel ind_users;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout_Btn;
    private javax.swing.JPanel logsBtn;
    private javax.swing.JPanel logs_Panel;
    private javax.swing.JPanel myInfoBtn;
    private javax.swing.JPanel myInfo_Panel;
    private javax.swing.JPanel parent;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JPanel signOffPanel;
    private javax.swing.JPanel signOffTaskBtn;
    private javax.swing.JPanel taskBtn;
    private javax.swing.JPanel tasks_Panel;
    private javax.swing.JPanel usersBtn;
    private javax.swing.JPanel users_Panel;
    // End of variables declaration//GEN-END:variables
}
